name: Regenerate PluginMaster
on:
  workflow_dispatch:
concurrency: regenerate

jobs:
  generate:
    name: Regenerate PluginMaster
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: Run generator
        run: .\Make-PluginMaster.ps1
      
      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Regenerate PluginMaster
          branch: ${{ github.head_ref || github.ref_name }}
          commit_user_name: GitHub Action
          commit_user_email: action@github.com
          commit_options: '--no-verify'
